//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ID_Child { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Paren { get; set; }
        public Nullable<int> Grp { get; set; }
        public Nullable<System.DateTime> DataBir { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Event { get; set; }
        public Nullable<int> DopZan { get; set; }
    
        public virtual Event Event1 { get; set; }
        public virtual Group Group { get; set; }
        public virtual Parents Parents { get; set; }
        public virtual Zanztia Zanztia { get; set; }
    }
}
