//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tich
    {
        public int ID_Tich { get; set; }
        public string FIOTic { get; set; }
        public string Tel { get; set; }
        public Nullable<int> GrpForChil { get; set; }
        public Nullable<int> ToEvent { get; set; }
        public Nullable<int> ToZant { get; set; }
        public string login_Tic { get; set; }
        public string password { get; set; }
        public Nullable<int> Rol { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Group Group { get; set; }
        public virtual Roul Roul { get; set; }
        public virtual Zanztia Zanztia { get; set; }
    }
}
