//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ID_Child { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Paren { get; set; }
        public Nullable<int> Grp { get; set; }
        public Nullable<System.DateTime> DataBir { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Event { get; set; }
        public Nullable<int> DopZan { get; set; }
        public string budjet { get; set; }
        public string Jelih { get; set; }
        public string Propis { get; set; }
    
        public virtual Event Event1 { get; set; }
        public virtual Group Group { get; set; }
        public virtual Parents Parents { get; set; }
        public virtual Zanztia Zanztia { get; set; }
    }
}
