//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tich()
        {
            this.Group = new HashSet<Group>();
            this.Zanat = new HashSet<Zanat>();
        }
    
        public int ID_Tich { get; set; }
        public string FIOTic { get; set; }
        public string Tel { get; set; }
        public Nullable<int> GrpForChil { get; set; }
        public Nullable<int> ToEvent { get; set; }
        public Nullable<int> ToZant { get; set; }
        public string login_Tic { get; set; }
        public string password { get; set; }
        public Nullable<int> Rol { get; set; }
        public Nullable<int> Pari { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Group { get; set; }
        public virtual Group Group1 { get; set; }
        public virtual Roul Roul { get; set; }
        public virtual Zanztia Zanztia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zanat> Zanat { get; set; }
    }
}
