//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zanat
    {
        public int ID { get; set; }
        public string DenNed { get; set; }
        public string Para1 { get; set; }
        public string Zam1 { get; set; }
        public string Para2 { get; set; }
        public string Zam2 { get; set; }
        public string Para3 { get; set; }
        public string Zam3 { get; set; }
        public string Para4 { get; set; }
        public string Zam4 { get; set; }
        public string Para5 { get; set; }
        public string Zam5 { get; set; }
        public Nullable<int> NomerUch { get; set; }
    
        public virtual Tich Tich { get; set; }
    }
}
